apiVersion: v2
name: lab-two-chart
description: A Helm chart for lab-02 OTUS-SA

type: application
version: 0.2
appVersion: "0.2"

dependencies:
  - name: postgresql
    version: 10.3.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgreslq.enabled
