replicaCount: 2

image:
  repository: itavgur/otus

application:
  port: 8000

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  protocol: TCP

postgresql:
  fullnameOverride: my-postgres
  enabled: true
  postgresqlUsername: bXl1c2Vy
  postgresqlPassword: cGFzc3dk
  postgresqlDatabase: myapp
  service:
    port: "5432"

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  hosts:
    - host: arch.homework
      paths: [
        { path: "/" }
      ]

serviceAccount:
  create: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

