replicaCount: 2

image:
  repository: itavgur/otus
  tag: "0.2"

application:
  port: 8000

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  protocol: TCP

externalPostgresql:
  serviceName: my-postgres
  postgresqlUsername: bXl1c2Vy
  postgresqlPassword: cGFzc3dk
  postgresqlDatabase: myapp
  postgresqlPort: "5432"

#global:
#  postgresql:
#    postgresqlDatabase: myapp
#    postgresqlUsername: myuser
#    postgresqlPassword: passwd

#  enabled: true
#  : myuser
#  postgresqlPassword: cGFzc3dk
#  postgresqlDatabase: myapp
#  service:
#    port: "5432"

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  hosts:
    - host: arch.homework
      paths: [
        { path: "/" }
      ]

serviceAccount:
  create: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

