{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lab-chart.fullname" . }}
  labels:
  {{- include "lab-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "lab-chart.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
  {{- include "lab-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: my-app-port
      path: /monitor/prometheus

  {{- end }}

---
  {{if .Values.postgresql.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-posgres-exporter
  labels:
spec:
  jobLabel: prometheus-posgres-exporter
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      app: prometheus-postgres-exporter
      release: postgres-exporter
  endpoints:
    - interval: 15m
      port: http
      path: /metrics

  {{- end}}
