apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-two-config
data:
  DB_NAME: {{.Values.externalPostgresql.postgresqlDatabase}}

---
apiVersion: v1
kind: Secret
metadata:
  name: lab-two-secret
type: Opaque
data:
  DB_USER: {{.Values.externalPostgresql.postgresqlUsername}}
  DB_PASS: {{.Values.externalPostgresql.postgresqlPassword}}
