apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-two-config
data:
  DB_NAME: {{.Values.postgresql.postgresqlDatabase}}
  DB_USER: {{.Values.postgresql.postgresqlUsername}}
  DB_PASS: {{.Values.postgresql.postgresqlPassword}}
