apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-two-config
data:
  DB_NAME: '{{.Values.postgresql.auth.database}}'
  DB_USER: '{{.Values.postgresql.global.postgresql.auth.username}}'

---
apiVersion: v1
kind: Secret
metadata:
  name: lab-two-secret
type: Opaque
data:
  DB_PASS: {{.Values.postgresql.postgresqlPassword}}
