---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v041
  namespace: app
  labels:
    app: app
    version: 0.4.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: 0.4.1
  template:
    metadata:
      name: lab-v041
      namespace: app
      labels:
        app: app
        version: 0.4.1
    spec:
      containers:
        - name: lab-v041
          image: itavgur/otus:0.4.1
          ports:
            - name: app-port
              containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: app-v041
  namespace: app
spec:
  selector:
    app: app
    version: 0.4.1
  ports:
    - port: 8000
      name: app-port
      targetPort: 8000
      protocol: TCP
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v042
  namespace: app
  labels:
    app: app
    version: 0.4.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: 0.4.2
  template:
    metadata:
      name: lab-v042
      namespace: app
      labels:
        app: app
        version: 0.4.2
    spec:
      containers:
        - name: lab-v042
          image: itavgur/otus:0.4.2
          ports:
            - name: app-port
              containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: app-v042
  namespace: app
spec:
  selector:
    app: app
    version: 0.4.2
  ports:
    - name: app-port
      port: 8000
      targetPort: 8000
      protocol: TCP
  sessionAffinity: None
  type: ClusterIP
