---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger

---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  namespace: jaeger
  name: jaeger

# also access via
# istioctl dashboard jaeger
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-query
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/part-of: jaeger
  name: jaeger-ui
  namespace: jaeger
spec:
  ports:
    - name: jaeger-ui
      port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: NodePort
