replicaCount: 1
fullnameOverride: app-service

image:
  repository: itavgur/otus_app
  tag: 0.5.0

application:
  port: 8000

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  protocol: TCP

postgresql:
  enabled: true
  fullnameOverride: my-postgres
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"

authCheckUrl:
  url: "http://auth-service:8001/check"

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  hosts:
    - host: arch.homework
      paths: [
        { path: "/person" },
        { path: "/health" }
      ]

serviceAccount:
  create: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

