apiVersion: v1
kind: Namespace
metadata:
  name: kiali

---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: kiali
spec:
  istio_namespace: "istio-system"
  istio_component_namespaces:
    prometheus: prometheus
    grafana: prometheus
    tracing: jaeger
  auth:
    strategy: "anonymous"
  external_services:
    istio:
      component_status:
        components:
          - app_label: istiod
            is_core: true
          - app_label: istio-ingressgateway
            is_core: false
          - app_label: istio-egressgateway
            is_core: false

    grafana:
      enabled: true
      in_cluster_url: "http://prometheus-grafana.prometheus:80"
      url: "http://prometheus-grafana.prometheus:80"
      auth:
        username: admin
        password: admin
        type: basic
        use_kiali_token: false
      component_status:
        namespace: "prometheus"
        app_label: "grafana"

    prometheus:
      url: "http://prom-prometheus.prometheus:9090"
      component_status:
        namespace: "prometheus"
        app_label: "prometheus"
        is_core: false

    tracing:
      enabled: true
      in_cluster_url: "http://jaeger-query.jaeger:16686"
      url: "http://jaeger-query.jaeger:16686"
      component_status:
        namespace: "jaeger"
        app_label: "jaeger"

# also access via
# istioctl dashboard jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: kiali-ui
  namespace: kiali
spec:
  selector:
    app: kiali
  ports:
    - name: kiali-ui
      port: 20001
      targetPort: 20001
      protocol: TCP
  type: NodePort
