order:
  replicaCount: 1
  name: order-service

  image:
    repository: ygmelnikov/otus_order
    tag: 0.6.1

  application:
    port: 8002

  probe:
    liveness:
      initDelayTime: 45
    readiness:
      initDelayTime: 45

  service:
    type: NodePort
    port: 8002
    targetPort: 8002
    protocol: TCP
  personServiceUrl: "http://person-service:8000/person"
  authCheckUrl: "http://auth-service:8001/check"
  redisHost: redis-master.default.svc.cluster.local

auth:
  replicaCount: 1
  name: auth-service

  image:
    repository: ygmelnikov/otus_auth
    tag: 0.6.1

  application:
    port: 8001

  service:
    type: NodePort
    port: 8001
    targetPort: 8001
    protocol: TCP
  personServiceUrl: "http://person-service:8000/person"

person:
  replicaCount: 1
  name: person-service
  image:
    repository: ygmelnikov/otus_person
    tag: 0.6.1

  application:
    port: 8000

  probe:
    liveness:
      initDelayTime: 45
    readiness:
      initDelayTime: 45

  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    protocol: TCP

  postgresql:
    fullnameOverride: postgres
    app:
      database: "myapp"
      username: root
      password: cm9vdA==
      port: "5432"
  authCheckUrl: "http://auth-service:8001/check"

postgresql:
  fullnameOverride: postgres
  auth:
    database: "myapp"
    username: root
    password: cm9vdA==
    schema: auth
    port: "5432"
  person:
    database: "myapp"
    username: root
    password: cm9vdA==
    schema: customers
    port: "5432"
  order:
    database: "myapp"
    username: root
    password: cm9vdA==
    schema: orders
    port: "5432"

ingress:
  enabled: true
  auth:
    - host: arch.homework
      paths: [
        { path: "/register" },
        { path: "/login" },
        { path: "/check" },
        { path: "/logout" }
      ]
  person:
    - host: arch.homework
      paths: [
        { path: "/person" }
      ]
  order:
    - host: arch.homework
      paths: [
        { path: "/order" }
      ]

serviceAccount:
  create: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

