{
 "title": "My-app-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{namespace=\"monitoring\"}[30s]))*100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"monitoring\"}[1m]))"
    }
   ]
  },
  {
   "title": "nginx rps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count[1m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "app-count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (http_server_requests_seconds_count{uri=~\"/health|/person\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "app rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{uri=~\"/health|/person\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "http errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{status!~\"2..\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname)(rate(pg_stat_database_tup_fetched[10m]))",
     "legendFormat": "fet: {{datname}}"
    },
    {
     "expr": "sum by (datname)(rate(pg_stat_database_tup_returned[10m]))",
     "legendFormat": "ret: {{datname}}"
    },
    {
     "expr": "sum by (datname)(rate(pg_locks_count[10m]))",
     "legendFormat": "lock:{{datname}}"
    }
   ]
  },
  {
   "title": "Latency, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum[1m])/rate(http_server_requests_seconds_count[1m])*1000)"
    }
   ]
  },
  {
   "title": "Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri,quantile) (http_server_requests_seconds{quantile =~ \"0.9|0.5|0.99\", uri !~ \"/monitor.*\"}) *1000",
     "legendFormat": "{{uri}}, {{quantile}}"
    },
    {}
   ]
  }
 ]
}