apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-two-config
data:
  DB_NAME: 'myapp'
  DB_URL: 'jdbc:postgresql://postgres:5432/myapp'

---
apiVersion: v1
kind: Secret
metadata:
  name: lab-two-secret
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: cm9vdA==
