apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-two-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-two-app
  template:
    metadata:
      labels:
        app: lab-two-app
    spec:
      containers:
        - name: lab-two
          image: itavgur/otus:0.2
          ports:
            - name: pseudo-web
              containerPort: 8000
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: lab-two-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: lab-two-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: lab-two-secret
                  key: DB_PASS

