apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab-two-ingress
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lab-two-service
                port:
                  number: 8000
  ingressClassName: nginx



