apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: lab-2
build:
  artifacts:
  - image: itavgur/otus
    context: lab-app
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - config.yaml
    - postgres.yaml
    - job.yaml
    - service.yaml
    - ingress.yaml
    - deployment.yaml
