replicaCount: 2

image:
  repository: itavgur/otus

application:
  port: 8000

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  protocol: TCP

postgresql:
  fullnameOverride: postgres
  auth:
    username: root
    existingSecret: lab-three-secret
    secretKeys:
      userPasswordKey: DB_PASS
      adminPasswordKey: DB_PASS
    database: "myapp"
  postgresqlPassword: cm9vdA==
  port: "5432"

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: [
        { path: "/" }
      ]

metrics:
  serviceMonitor:
    enabled: true

serviceAccount:
  create: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
