apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "app.fullname" . }}
data:
  DB_NAME: {{.Values.postgresql.postgresqlDatabase}}
  DB_USER: {{.Values.postgresql.postgresqlUsername}}
  DB_PASS: {{.Values.postgresql.postgresqlPassword}}
  AUTH_CHECK_URL: {{.Values.authCheckUrl.url}}
