apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "app.fullname" . }}
data:
  DB_NAME: '{{.Values.postgresql.app.database}}'
  DB_USER: '{{.Values.postgresql.app.username}}'
  AUTH_CHECK_URL: '{{.Values.authCheckUrl.url}}'

---
apiVersion: v1
kind: Secret
metadata:
  name: {{include "app.fullname" . }}
type: Opaque
data:
  DB_PASS: {{.Values.postgresql.app.password}}
