replicaCount: 2

image:
  repository: itavgur/otus

application:
  port: 8000

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  protocol: TCP

global:
  postgresql:
    auth:
      username: root
      password: root
      database: "myapp"

postgresql:
  fullnameOverride: postgres
  enabled: true
  postgresqlUsername: cm9vdA==
  postgresqlPassword: cm9vdA==
  postgresqlDatabase: myapp
  service:
    port: "5432"

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  hosts:
    - host: arch.homework
      paths: [
        { path: "/" }
      ]

serviceAccount:
  create: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80