# also access via
# istioctl dashboard prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-ui
  namespace: prometheus
spec:
  ports:
    - name: prometheus-ui
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
    prometheus: prom-prometheus
  type: NodePort

# also access via
# istioctl dashboard grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-ui
  namespace: prometheus
spec:
  ports:
    - name: grafana-ui
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
  type: NodePort

