apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "auth.fullname" . }}
data:
  DB_NAME: '{{.Values.postgresql.auth.database}}'
  DB_USER: '{{.Values.postgresql.auth.username}}'
  PERSON_URL: '{{.Values.personServiceUrl.url}}'

---
apiVersion: v1
kind: Secret
metadata:
  name: {{include "auth.fullname" . }}
type: Opaque
data:
  DB_PASS: {{.Values.postgresql.auth.password}}