apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.person.name}}
spec:
  template:
    metadata:
      name: {{.Values.person.name}}_sql_populate
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db
          image: postgres:latest
          command:
            - sh
            - "-c"
            - until pg_isready -h {{ include "postgresql.fullname" . }};
              do echo waiting for database to start; sleep 3; done;
      containers:
        - name: post-install-job
          image: postgres:latest
          command:
            - sh
            - "-c"
            - psql postgres://{{.Values.postgresql.person.username}}:{{.Values.postgresql.person.password | b64dec}}@{{ include "postgresql.fullname" . }}/{{.Values.postgresql.person.database}} << 'EOF'

              INSERT INTO customers.city (name)
              VALUES ('Moscow'),
              ('Irkutsk');

              EOF

  backoffLimit: 4
